# Generated by Django 3.0.10 on 2022-05-22 21:11

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.BigIntegerField(blank=True, null=True, verbose_name='Order')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Order Number')),
                ('customer', models.BigIntegerField(blank=True, null=True, verbose_name='Customer')),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Method')),
                ('payment_status', models.CharField(blank=True, choices=[('PE', 'PENDING'), ('PR', 'PROCESSING'), ('SF', 'SUCCESSFUL'), ('FA', 'FAILED'), ('RE', 'REFUND')], default='PE', max_length=2, null=True, verbose_name='Payment Status')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Amount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
