# Generated by Django 3.0.10 on 2022-05-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_status',
            new_name='status',
        ),
    ]
