version: '3.9'

x-postgres-variables: &postgres-variables
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: payment
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin

services:
  postgres:
    image: 'postgres'
    container_name: 'payment_postgres'
    environment:
      <<: *postgres-variables
    ports:
      - '5435:5432'
    networks:
      - payment_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: 'adminer'
    container_name: 'payment_adminer'
    depends_on:
      - postgres
    ports:
      - '8083:8080'
    networks:
      - payment_network

  payment:
    build:
      context: .
      dockerfile: ./compose/django/local/Dockerfile
    container_name: 'payment'
    environment:
      <<: *postgres-variables
      API_KEY: '76ed9f63-1d17-4a4c-a16e-a970b2e7e3af'
      DJANGO_SECRET: '*bg@t@8c3h#c$$k2)6rog7ziz0907&_4-*80c(jq&o9uv&ocq+p'
    depends_on:
      - postgres
    ports:
      - '8003:8000'
    networks:
      - payment_network
    volumes:
      - .:/app

networks:
  payment_network:
    driver: bridge

volumes:
  pgdata:
