version: '3.9'

services:
  ordering:
    build:
      context: .
      dockerfile: ./compose/django/local/Dockerfile
    container_name: 'ordering'
    environment:
      API_KEY: '76ed9f63-1d17-4a4c-a16e-a970b2e7e3af'
      DJANGO_SECRET: '*bg@t@8c3h#c$$k2)6rog7ziz0907&_4-*80c(jq&o9uv&ocq+p'

      # Product Service
      PRODUCT_SERVICE_URL: 'http://product:8000'
      PRODUCT_CREATE_API: '/api/product/v1/create/'
      PRODUCT_UPDATE_API: '/api/product/v1/update/{id}/'
      PRODUCT_DETAIL_API: '/api/product/v1/{id}'
      PRODUCT_LIST_API: '/api/product/v1/list/'

      # Order Service
      ORDER_SERVICE_URL: 'http://order:8000'
      ORDER_CREATE_API: '/api/order/v1/create/'
      ORDER_UPDATE_API: '/api/order/v1/update/{id}/'
      ORDER_DETAIL_API: '/api/order/v1/{id}/'
      ORDER_LIST_API: '/api/order/v1/list/'

      # Payment Service
      PAYMENT_SERVICE_URL: 'http://payment:8000'
      PAYMENT_CREATE_API: '/api/payment/v1/create/'
      PAYMENT_UPDATE_API: '/api/payment/v1/update/{id}/'
      PAYMENT_DETAIL_API: '/api/payment/v1/{id}/'
      PAYMENT_LIST_API: '/api/payment/v1/list/'
      ORDER_PAYMENT_UPDATE_API: '/api/payment/v1/update/{order}/'
      ORDER_PAYMENT_DETAIL_API: '/api/payment/v1/{order}/'

      # Cart Service
      CART_SERVICE_URL: 'http://cart:8000'
      CART_UPDATE_API: '/api/cart/v1/update/{customer}/'
      CART_DETAIL_API: '/api/cart/v1/{customer}/'
      CART_DELETE_API: '/api/cart/v1/clear/{customer}/'
    ports:
      - '8005:8000'
    networks:
      - ordering_network
      - product_product_network
      - order_order_network
      - payment_payment_network
      - cart_cart_network
    volumes:
      - .:/app

networks:
  ordering_network:
    driver: bridge
  product_product_network:
    external: true
  order_order_network:
    external: true
  payment_payment_network:
    external: true
  cart_cart_network:
    external: true
