# Generated by Django 3.0.10 on 2022-05-22 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_deleted')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Order Number')),
                ('customer', models.BigIntegerField(blank=True, null=True, verbose_name='Customer')),
                ('payment', models.BigIntegerField(blank=True, null=True, verbose_name='Payment')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Tax Amount')),
                ('shipping_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True, verbose_name='Shipping Amount')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Total Amount')),
                ('status', models.CharField(blank=True, choices=[('PL', 'PLACED'), ('PR', 'PROCESSING'), ('OW', 'ON_THE_WAY'), ('OD', 'OUT_FOR_DELIVERY'), ('DL', 'DELIVERED'), ('RT', 'RETURN'), ('FL', 'FAILED'), ('CL', 'CANCELLED'), ('EX', 'EXCHANGE')], default='PL', max_length=2, null=True, verbose_name='Order Status')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_deleted')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product', models.BigIntegerField(blank=True, null=True, verbose_name='Product')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Price')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
